update-initramfs: Fix error message to be more generic
The orinigal use case was:
update-initramfs  -k $(uname -a) -t -u

The current bugreport names:
update-initramfs -k 2.6.38-2p -c /boot/initrd.img-2.6.38-2p

Closes: #627547
Signed-off-by: maximilian attems <max@stro.at>

diff --git a/update-initramfs b/update-initramfs
--- a/update-initramfs
+++ b/update-initramfs
@@ -455,7 +455,7 @@ done
 shift $((${OPTIND} - 1))
 
 if [ $# -ne 0 ]; then
-	echo "Invalid argument for option -k." >&2
+	echo "Invalid arguments see belows help:" >&2
 	usage
 fi
 
