scripts/local: add error checking for root mount and root fs support.

diff --git a/scripts/local b/scripts/local
--- a/scripts/local
+++ b/scripts/local
@@ -66,12 +66,40 @@ mountroot ()
 		roflag=-w
 	fi
 
-	# FIXME This has no error checking
 	modprobe ${FSTYPE}
 
-	# FIXME This has no error checking
-	# Mount root
-	mount ${roflag} -t ${FSTYPE} ${ROOTFLAGS} ${ROOT} ${rootmnt}
+	# Look for $FSTYPE in /proc/filesystems (without using grep)
+	$(while read line; do
+		if [ "${line}" != "${line%${FSTYPE}}" ]; then
+			exit 0
+		fi
+	done < /proc/filesystems
+	exit 1)
+
+	if [ $? -ne 0 ]; then
+		echo "WARNING!  Support for filesystem ${FSTYPE} seems to be missing"
+		echo "  ${FSTYPE} is necessary to mount the root fs (${ROOT})"
+	fi
+
+	# Loop until something is mounted on ${rootmnt}
+	while [ 1 ]; do
+		mount ${roflag} -t ${FSTYPE} ${ROOTFLAGS} ${ROOT} ${rootmnt}
+
+		$(while read source target options; do
+			if [ "${target}" = "${rootmnt}" ]; then
+				exit 0
+			fi
+		done < /proc/mounts
+		exit 1)
+
+		if [ $? -eq 0 ]; then
+			break
+		fi
+
+		echo "ALERT!  Unable to mount root filesystem (${ROOT}).  Dropping to a shell!"
+		echo "	Check your root= boot argument (cat /proc/cmdline)"
+		panic "	Check for missing modules (cat /proc/modules), or device files (ls /dev)"
+	done
 
 	[ "$quiet" != "y" ] && log_begin_msg "Running /scripts/local-bottom"
 	run_scripts /scripts/local-bottom
